### ISSUE TITLE
Please consolidate Versioning! You check in "Main" but break HA updates with that! Problem inside: *After"update" lost yaml file "deye_2mppt.yaml"*

### ISSUE THREAD

**Issue by Ulfmerbold2000** [StephanJoubert/home_assistant_solarman#297]
I've installed "main" version and got my Deye Sun600 G3 working with deye_2mppt.yaml

Today Hacs noted me an "update" from my version to "1.4.3", while my main version was labeled with "1.4.3" too.

Now, the yaml file "deye_2mppt.yaml" is gone and nothing works...

At all i would say the error is in the generation of the releases...the 1.4.3 release isnt any kind of "full" version, half of the
updated files missing and the files which are in "main" version but not in "1.4.3" will be deleted after update process...
Makes it hard to work with...

**Comment by secdude** [comment]
Same here, but right after new install. Manually adding deye_2mppt.yaml from GitHub did not help, it doesn’t show up in the drop-down after ha restart. Manually adding the sensor with platform solarman also did not help, no devices/entities showing up. Currently can’t find relevant logs.

side-note, probably unrelated: esphome update shown but finishing without upgrading

**Comment by secdude** [comment]
Tried to fix the const.py as https://github.com/StephanJoubert/home_assistant_solarman/issues/254 

suggests, file shows up in drop-down now. But SOLARMAN fails to load fixing this error:
```

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/solarman/__init__.py:18 
Integration: Solarman (documentation, issues) 
First occurred: 14:41:07 (2 occurrences) 
Last logged: 14:41:36

Error setting up entry 192.168.2.187 for solarman
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/solarman/__init__.py", line 18, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

```

**Comment by superwolfi82** [comment]
Hello Everyone 

Just got an Deye Sun600 G3  and it works without Issues  with the deye_4mppt.yaml configuration  ..
 only thing: manual adding the deye didn't work I useful autodiscovery (+ restart and after 5 min everything Worker as expected)

**Comment by vordenken** [comment]
> Tried to fix the const.py as #254
> 
> suggests, file shows up in drop-down now. But SOLARMAN fails to load giving this error:
> 
> ```
> 
> Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> 
> Logger: homeassistant.config_entries
> Source: custom_components/solarman/__init__.py:18 
> Integration: Solarman (documentation, issues) 
> First occurred: 14:41:07 (2 occurrences) 
> Last logged: 14:41:36
> 
> Error setting up entry 192.168.2.187 for solarman
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/solarman/__init__.py", line 18, in async_setup_entry
>     hass.config_entries.async_setup_platforms(entry, PLATFORMS)
> AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
> ```

I got the same error after updating to 2023.5.3 from 2023.4.6 - I rolled back the update for now and it works again.

I also got this message in the logs:
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 13:08:20 (1 occurrences)
Last logged: 13:08:20

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for solarman using this method at custom_components/solarman/__init__.py, line 18: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
```

**Comment by dommuh** [comment]
I have the same problem. 
Copied the code from 2mppt to 4mppt.yaml and selected the 4mppt. 
Works for me but it's only a workaround.

**Comment by DocSnyd3r** [comment]
Same here hat to copy the 2mppt in and add to const.py. Works for me, was new install no upgrade.

**Comment by ChristophCaina** [comment]
Hi, yes - I also had to select the "main" version in order to get the 2mppt.yaml...
Now, HomeAssistant is telling me, that there's an update to 1.4.3 available...

Would be great, if you could stick to a schema with the version numbers... :)
